Make docs website, fix spelling in docs.
VukkyLtd/SaladBind pull request #23
Opened 2021-08-03 17:41 UTC by WalkxCode

Did some fuckery with docs yes.

2021-08-03 17:45 UTC, WalkxCode commented
Add github pages to /docs and it'll work.

2021-08-04 08:25 UTC, Vukkyy requested changes

2021-08-04 08:26 UTC, Vukkyy reviewed
oops nvm lol

2021-08-04 12:50 UTC, vtheskeleton requested changes
(i havent had time to look trough this but thats just something i noticed.)

2021-08-04 13:13 UTC, WalkxCode commented on package.json
> +  "name": "SaladBind",
didnt know lol

2021-08-05 08:56 UTC, WalkxCode commented
@Vukkyy i want review plz

2021-08-06 11:39 UTC, vtheskeleton commented
amogus

2021-08-06 11:39 UTC, closed without merging