Adds Discord Rich Presence functionality to SaladBind
VukkyLtd/SaladBind pull request #28
Opened 2021-08-04 14:21 UTC by memedmusic

--------- This is just copy-pasted from my failed attempt ------------
This is my first contribution on GitHub, so hopefully I've done everything right.

With this new code users can opt-in to have a discord rich presence display one of 3 different status':

In main menu
Configuring miners
Mining with {miner name} (will also display how long the user has been mining for)
Why I think this is a good idea:

Extra promotion for SaladBind
Can be used to inform a user if their miner is still running
If the user doesn't want to have a rich presence, they can turn it off at anytime using the Configure SaladBind interface

I have tested the compiled app on windows and to my knowledge it is all working fine.

2021-08-04 15:53 UTC, WalkxCode approved these changes
Walky approves 🦶

2021-08-04 16:06 UTC, WalkxCode commented on setup.js
> +        message: chalk.yellow("Allow Discord rich presence to be shown? (May require app restart)"),
Maybe "Enable Discord Rich Presence?" would sound better?

2021-08-04 21:41 UTC, memedmusic commented on setup.js
> +        message: chalk.yellow("Allow Discord rich presence to be shown? (May require app restart)"),
Yeah, it does. I just changed it

2021-08-05 08:49 UTC, WalkxCode approved these changes

2021-08-06 11:47 UTC, vtheskeleton requested changes
Please do not change whitespace from tabs to spaces.

2021-08-06 12:17 UTC, vtheskeleton commented on presence.js
> +var { config } = require('process');
> var { config } = require('process');
What is this for?

2021-08-06 13:15 UTC, memedmusic commented on presence.js
> +var { config } = require('process');
I have no idea. I must have left it there while I was testing stuff. I'll remove it

2021-08-06 13:33 UTC, vtheskeleton requested changes
Great, now just the whitespace and I can merge this

2021-08-06 13:34 UTC, memedmusic commented
oh god what did i do aaaaaaaa

2021-08-06 13:50 UTC, memedmusic commented
what lmao am i just stupid or is it still spaces

2021-08-06 14:03 UTC, vtheskeleton requested changes
one more :(

2021-08-06 14:03 UTC, vtheskeleton commented on mining.js
> -			}
mining.js is still on spaces

2021-08-06 14:05 UTC, vtheskeleton commented
i failed wtf
time to try again

2021-08-06 14:06 UTC, vtheskeleton approved these changes
good enough

2021-08-06 14:06 UTC, merged

2021-08-06 14:07 UTC, memedmusic commented
Sorry for the extra hassle. Thanks for your help.