Autoupdate functionality
VukkyLtd/SaladBind pull request #32
Opened 2021-08-06 09:41 UTC by memedmusic

What this code does:
When SaladBind detects that an update is avaliable, instead of just telling the user the link to download the latest version they are prompted with a menu asking them if they want to download the latest update.
If the user does decide to update, the latest release for their os will be downloaded to the folder which the old SaladBind is found.

If a user is on windows, after the update finishes downloading it will be opened after 5 seconds. 
If a user is on linux or mac they will be told the latest update has finished downloading.

I have only tested this on windows (compiled and uncompiled), but I don't see why it wouldn't work on other os'

I'll attatch a video, it should be a bit easier to understand

https://user-images.githubusercontent.com/55370047/128491115-7d1ce7f8-5fac-4c66-a1a2-d4ac5ba07a28.mp4

2021-08-06 09:52 UTC, TheBlueBurger commented
Does this work on compiled?

2021-08-06 10:07 UTC, memedmusic commented
> Does this work on compiled?

 Indeed it does

2021-08-06 11:51 UTC, vtheskeleton requested changes
Looks good with the exception of whitespace being converted to spaces. Please keep it as tabs

2021-08-06 11:57 UTC, memedmusic commented
> Looks good with the exception of whitespace being converted to spaces. Please keep it as tabs

Will do. I'll change everything over as soon as I get a chance

2021-08-06 12:38 UTC, vtheskeleton approved these changes
I changed the intendation, looks good.
I am going to test it myself and after that merge

2021-08-06 12:40 UTC, TheBlueBurger commented
Maybe make a "remind never"?

2021-08-06 12:41 UTC, vtheskeleton commented
> Maybe make a "remind never"?

why would you not want updates?

2021-08-06 12:42 UTC, vtheskeleton requested changes
Please make it delete the old version, people are stupid and may not know which one to open

2021-08-06 13:17 UTC, memedmusic commented
> Please make it delete the old version, people are stupid and may not know which one to open

I was hoping you wouldn't ask that haha. I'll see what I can do 👍

2021-08-06 13:22 UTC, TheBlueBurger commented
> Please make it delete the old version, people are stupid and may not know which one to open

Don't know if it will be possible due to the old version is running, but maybe pkg does some weird stuff so it isn't that process that's running

2021-08-06 13:24 UTC, vtheskeleton commented
> > Please make it delete the old version, people are stupid and may not know which one to open
> 
> Don't know if it will be possible due to the old version is running, but maybe pkg does some weird stuff so it isn't that process that's running

just have the old one process.exit(0)
and the new one look for old versions and delete it

2021-08-06 13:26 UTC, memedmusic commented
> > Please make it delete the old version, people are stupid and may not know which one to open
> 
> Don't know if it will be possible due to the old version is running, but maybe pkg does some weird stuff so it isn't that process that's running

It is probably possible on windows by using the taskkill cmd command, not sure about other os' though.

2021-08-06 13:27 UTC, vtheskeleton commented
> > > Please make it delete the old version, people are stupid and may not know which one to open
> > 
> > 
> > Don't know if it will be possible due to the old version is running, but maybe pkg does some weird stuff so it isn't that process that's running
> 
> It is probably possible on windows by using the taskkill cmd command, not sure about other os' though.

why would you need to taskkill??
just process.exit after running the other one!

2021-08-06 13:29 UTC, memedmusic commented
> why would you need to taskkill??
> just process.exit after running the other one!

I will certainly give that a try.

2021-08-07 01:49 UTC, memedmusic commented
I changed the code so on startup, if there are multiple files which have "saladbind" or "salad bind" in their name they will be deleted.

https://user-images.githubusercontent.com/55370047/128584209-c007dab7-7f9f-46f2-afcb-e52780384e0c.mp4

2021-08-07 08:06 UTC, vtheskeleton commented on update.js
> +			}, 5000)
Why does it wait 5 seconds?

2021-08-07 08:19 UTC, memedmusic commented on update.js
> +			}, 5000)
After downloading the latest update, saladbind will open it.
The process of opening the new saladbind takes 5 seconds (using SetTimeout) + a variable amount for the computer to process it.
The script does not account for those extra few seconds of processing, it just continues on.
After the newer version of saladbind is requested to open the old script will close after 5 seconds because if the script closes before the new version of saladbind opens then the new version of saladbind wont actually open.

The 5 second wait is to ensure that the older script has had enough time to close, as if it is still open then it wont be able to be removed.

I hope this makes at least a little bit of scence

2021-08-07 08:24 UTC, vtheskeleton commented on update.js
> +			}, 5000)
well why does the old one have the 5 second timeout though? makes no sense

2021-08-07 08:28 UTC, memedmusic commented on update.js
> +			}, 5000)
If the old one closes instantly then the new version wont actually open. As i said before there is a second or two of extra processing time, its just the same as clicking on an exe file and it doesnt open for a second. For some reason the newer version wouldnt open unless I accounted for those extra few seconds of processing time, hence the 5 second timeout

2021-08-07 08:34 UTC, vtheskeleton approved these changes
seems hacky but okay then haha

2021-08-07 08:34 UTC, merged