Systeminfo cache
VukkyLtd/SaladBind pull request #35
Opened 2021-08-07 23:32 UTC by memedmusic

resolves #8 kinda i guess.
Instead of checking the system information after you click start mining, this code caches your system information and uses it to remove the checking system information loading screen. 

There is a once-off generating cache loading screen, but after that the cache automatically updates in the background!
If a user wants to delete their cache they can always navigate to the data folder and remove the cache.json file.

This video is comparing the non-cache version with the cache version sorta.
https://user-images.githubusercontent.com/55370047/128616222-4305da97-06f3-4cac-9ed7-381009e37318.mp4

2021-08-07 23:40 UTC, Vukkyy requested changes
you did the tabs to spaces thing again...

2021-08-07 23:41 UTC, memedmusic commented
goddamit haha one sec

2021-08-07 23:43 UTC, memedmusic commented
Updated mining.js, and i think getMachine.js is fine

2021-08-22 15:33 UTC, vtheskeleton approved these changes

2021-08-22 15:33 UTC, merged