Changelogs in the menu
VukkyLtd/SaladBind pull request #57
Opened 2021-08-31 12:51 UTC by Tpelaaja

You can go to a changelogs page if you want thru this commit.

It uses almost the same function as the update.js fetching the changelogs but modified to work with this.

2021-08-31 12:52 UTC, TheBlueBurger requested changes
Why not show this when it's on the "please update saladbind" screen too

2021-08-31 12:53 UTC, Tpelaaja commented
its already on it!

2021-08-31 12:53 UTC, TheBlueBurger commented
Oh nevermind I forgot about that

2021-08-31 12:54 UTC, TheBlueBurger approved these changes

2021-08-31 12:56 UTC, Tpelaaja commented
I updated it because I had a shitty bug
(bug was said "Changelog of 1.3.1 is available!" removed the last part to be  just "Changelog of 1.3.1")

2021-08-31 13:12 UTC, memedmusic commented on src/index.js
> +			const spinner = ora('Checking for updates...').start();
Instead of Checking for updates maybe do something along the lines of Fetching Changelog

2021-08-31 13:18 UTC, Tpelaaja commented on src/index.js
> +			const spinner = ora('Checking for updates...').start();
> Instead of Checking for updates maybe do something along the lines of Fetching Changelog

yeah its just an quick implementation. I could change it if I wanted but thats a super small detail.

ill probably fix it soon

2021-08-31 13:19 UTC, Tpelaaja commented on src/index.js
> +			const spinner = ora('Checking for updates...').start();
fixed

2021-09-02 13:01 UTC, vtheskeleton reviewed
fine i gues slol

2021-09-02 13:01 UTC, merged