Added us2 to the regions list, wasted 9 hours of my life.
VukkyLtd/SaladBind pull request #61
Opened 2021-09-04 06:57 UTC by RuhmitSahu

The title is pretty self-explanatory, I added us2 to the regions list for ethash, while also keeping it removed from etchash.

2021-09-07 08:49 UTC, vtheskeleton requested changes
This PR has a variety of issues
bad practices, leaving in debugging code in comments, it actually just not working right with it being shown on nicehash and just generally screwing up formatting

2021-09-07 08:49 UTC, vtheskeleton commented on src/mining.js
> +			console.log(chalk.bold.cyan(`Ignore "us2" on NiceHash lol -Plerion`))
bruh.

2021-09-07 08:50 UTC, vtheskeleton commented
I dont feel like this pr is ready to be added at all
Make an issue on it and I can implement it myself

2021-09-07 09:50 UTC, vtheskeleton commented
We have decided that this pr is too big of a mess

2021-09-07 09:50 UTC, closed without merging

2021-09-10 05:05 UTC, RuhmitSahu commented
ouch