Automatically get miner id by logs on first start
VukkyLtd/SaladBind pull request #62
Opened 2021-09-07 07:50 UTC by memedmusic

Some people have mentioned it on discord, so i did it.
I tested it and i've found no bugs (yay)

2021-09-07 08:13 UTC, vtheskeleton requested changes
if you find them then you should ask the user if they want to use that one, if yes, cool continue to menu, if not then let them do the setup.

2021-09-07 08:29 UTC, memedmusic commented
Cool, that should be all done

2021-09-07 08:30 UTC, vtheskeleton commented
me when ask people questions
can you request a review next time though

2021-09-07 08:30 UTC, vtheskeleton commented
oh wait you just did

2021-09-07 08:32 UTC, vtheskeleton commented on src/setup.js
> +			run(false, true)
whart?? run only takes one argument no?

2021-09-07 08:32 UTC, vtheskeleton commented on src/setup.js
> +			run(false, true)
i may be blind but im not seeing any signs of actually asking for the things either

2021-09-07 08:35 UTC, memedmusic commented on src/setup.js
> +			run(false, true)
Asking for things on line 36-49, and yeah run only does take 1 arg, i forgot to remove it lol

2021-09-07 08:38 UTC, vtheskeleton commented
my brain is hurting

2021-09-07 08:38 UTC, vtheskeleton commented
what the fuck is this spaghetti

2021-09-07 08:39 UTC, memedmusic commented
more spaghetti = more better :D

2021-09-07 08:39 UTC, vtheskeleton commented
kill me

2021-09-07 09:50 UTC, vtheskeleton commented
![image](https://user-images.githubusercontent.com/47392011/132324388-3a81648f-64a9-4af0-b3da-a25e2bb5034d.png)

2021-09-10 10:32 UTC, vtheskeleton commented
Closing this after our discussion on discord. Still open to the idea if issues are fixed though

2021-09-10 10:32 UTC, closed without merging